config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'prescriptions#index'

  resources :sessions
  delete '/sessions', to: 'sessions#destroy'
  resources :users
  resources :prescriptions
  get '/prescriptions/view/:id', to: 'prescriptions#display'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :prescriptions
end

app/models/prescription.rb
class Prescription < ApplicationRecord
    belongs_to :user
    belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    validates :email, presence: true

    has_many :prescriptions
    has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
      user_id = session[:user_id]
      user_id && User.find(user_id)
  end
  
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
    def index
        render "index"
    end

    def show
        @prescription = Prescription.where(id: params[:id]).first
        if @prescription
            msg = { :status => "ok"}
       else
            msg = { :status => "fail"}
        end
        respond_to do |format|
            format.json  { render :json => msg }
        end
    end

    def display
        @prescription = Prescription.where(id: params[:id]).first
        render "collection", :locals => { :prescription => @prescription }
    end

    def qrcodevalidation
        # Parse QR Code and check if entry exists in database
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email])
  
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to root_url
        else
            render :new
        end
    end
  
    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new
    
        # Populate user hash
        @user.email = params[:user][:email]
    
        # These two fields are used by bcrypt to generate the password digest
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
    
        if @user.save
          # In controllers we use url
          # In views we use path
          redirect_to root_url
        else
          render :new
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InTag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

  <link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/flick/jquery-ui.css" />
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar is-info" role="navigation" aria-label="main navigation">
  <div class="container">
    <!-- logo -->
    <div class="navbar-brand">
      <a class="navbar-item">InTag</a>
    </div>

    <!-- menu -->
    <!-- <div class="navbar-menu"> -->
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <% if current_user %>
              <p class="control">
                <a class="navbar-item" style="display:inline;">Welcome <%= current_user.email %></a>
              </p>

              <p class="control">
                <a class="navbar-item" style="display:inline;"><%= link_to 'Logout', sessions_path, method: :delete %></a>
              </p>
            <% else %>
              <p class="control">
                <a class="navbar-item" id="newUserAnchor"><%= link_to 'New User', new_user_path %></a>
              </p>
              <p class="control">
                <a class="navbar-item is hoverable" id="loginAnchor"><%= link_to 'Login', new_session_path %></a>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    <!-- </div> -->
  </div>
</nav>

<section class="hero is-fullheight is-dark is-bold">
    <div class="hero-body">
        <div class="container">
            <%= yield %>
        </div>
    </div>
</section>
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>InTag</strong> by <a>Team 18</a>.
      </p>
    </div>
  </div>
</footer>
</body>
</html>

app/views/prescriptions/collection.html.erb
<h1 class="title has-text-centered"> Prescrption ID:<%= @prescription.id %></h1>
<div class="box" style="margin:0 auto;height:500px;width:70%">
    <!--div class="box" style="width:50%;float:left"-->
        <% @prescription.attributes.each do |attr_name, attr_value| %>
            <div>
            <%= attr_name %>: <%= attr_value %>
            </div>
        <% end %>
    <!--/div-->
</div>

app/views/prescriptions/index.html.erb
<h1 class="title has-text-centered">Enter Prescription ID or Click QR Code to Scan</h1>
<div class="box" style="margin:0 auto;height:300px;width:70%">
    <div class="box" style="width:50%;float:left">
        <!-- insert caption , utilizing forms module-->
        <div class="field">

        </div>
        <input id="theInput" type="text" class="input" placeholder="Enter ID"/>
        <div class="field">

        </div>

        <a id="searchSubmit" class="button is-success">Search</a>
    </div>
    <div id="videoDiv" class="box" style="float:right">
        <img id="qrImage" src="https://d30y9cdsu7xlg0.cloudfront.net/png/138360-200.png" style="display:block;margin-left: auto;margin-right: auto;"/> 
    </div>
</div>

<script>
    // QR Code Scanning  
    //new QRCode(document.getElementById("videoDiv"), "this is a test QR Code");
    $("#qrImage").on('click', function() {
        $("#qrImage").remove();
        $("#videoDiv").append("<video id='preview'></video>");
        let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
        scanner.addListener('scan', function (content) {
          console.log(content);
          // Make request to server
          $.getJSON(
              // QR Code value designed specific to application...maybe pad with arbitrary data??
              location.href + content,
              // Response Obj
              function(data) {
                if(data["status"] === "fail") {
                    console.log("ID doesn't exist");
                } else {
                    location.replace(location.href + "prescriptions/view/" + data["value"]);
                }
              }
          );
        });
        Instascan.Camera.getCameras().then(function (cameras) {
          if (cameras.length > 0) {
            scanner.start(cameras[0]);
          } else {
            console.error('No cameras found.');
          }
        }).catch(function (e) {
          console.error(e);
        });
    });

    $("#searchSubmit").on('click', function() {
        // Retrive input, trim first and convert into a number
        initialValue = $("#theInput").val();
        let inputValue = Number(initialValue);
        console.log("Value of input was " + inputValue);

        // Check if the number is actually a number...
        if(!isNaN(inputValue)) {
            console.log("In here");
            // Fetch from the server
            $.getJSON(
                
                "/prescriptions/" + inputValue,
                function(data) {
                    console.log(data);
                    if(data["status"] === "fail") {
                        console.log("ID doesn't exist");
                    } else {
                        location.replace(location.href + "prescriptions/view/" + inputValue);
                    }
                }
            );
        }
    });

</script>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<!-- if we don't do this and submit a form with no password, it rollbacks the transaction, we won't know about it -->
<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @user do |f| %>
    <div class='field'>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div class='field'>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div class='field'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit 'Sign Up' %>
<% end %>